# Generated by Django 3.1.6 on 2021-02-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_billingaddress_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(max_length=5),
        ),
    ]
