# Generated by Django 3.1.6 on 2021-03-02 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210302_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='billing_address',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='core.billingaddress'),
        ),
    ]
