# Generated by Django 3.1.6 on 2021-03-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
    ]
